const { application } = require('express');
const { Schema, model } = require('../connection')

const userSchema = new Schema({
    SchoolName: String,
    SchoolAddress: String,
    schoolDetail:String,
    state:String,
    fee1: String,
    fee2: String,
    fee3: String,
    fee4: String,
    fee5: String,
    fee6: String,
    fee7: String,
    fee8: String,
    fee9: String,
    fee10: String,
    fee11: String,
    fee12: String,
    email: String,
    phone: String,
    Schoolimage:String,
    Schoolimage1:String,
    Schoolimage2:String,
    Schoolimage3:String,
    Schoolimage4:String,
    Schoolimage5:String,
    SchoolType:String,
    TeacherCount:String,
    ClassRoom:String,
    SecPerClass:String,
    Year:String,
    event1:String,
    event2:String,
    event3:String,
    event4:String,
    Sports1:String,
    Sports2:String,
    comp1:String,
    comp2:String,
    comp3:String,
    comp4:String,
    AdvanceFsce1:String,
    AdvanceFsce2:String,
    AdvanceFsce3:String,
    let:String,
    lng:String,
    district:String,

})

module.exports = model('addicseBord',
    userSchema);