const { application } = require('express');
const { Schema, model } = require('../connection')

const userSchema = new Schema({
    SchoolName: String,
    SchoolAddress: String,
    schoolDetail:String,
    state:String,
    email: String,
    phone: String,
    SchoolimageLogo:String,
    Gallaryimage1:String,
    Gallaryimage2:String,
    Gallaryimage3:String,
    Gallaryimage4:String,
    Gallaryimage5:String,
    parentSay1:String,
    parentName1:String,
    parentImage1:String,
    studentName1:String,
    studentClass1:String,
    parentSay2:String,
    parentName2:String,
    parentImage2:String,
    studentName2:String,
    studentClass2:String,
    parentSay3:String,
    parentName3:String,
    parentImage3:String,
    studentName3:String,
    studentClass3:String,
    parentSay4:String,
    parentName4:String,
    parentImage4:String,
    studentName4:String,
    studentClass4:String,
    district:String,
    head1: String,
    head2: String,
    info1: String,
    info2: String,
    Facilities1: String,
    FacilitiesImage1: String,
    Facilities2: String,
    FacilitiesImage2: String,
    Facilities3: String,
    FacilitiesImage3: String,
    Facilities4: String,
    FacilitiesImage4: String,
})

module.exports = model('addupBord',
    userSchema);